#include "ui_controls.h"
#include "ui_localize.h"
#include "ui_dropdown.h"

static UiControlInstance *ui_controls_instance(UiControlSet *set,int id){unsigned i;if(!set)return 0;for(i=0;i<set->instance_count;i++)if(set->instances[i].spec&&set->instances[i].spec->id==id)return &set->instances[i];return 0;}
static void ui_controls_discard(UiControlSet *set){unsigned i;if(!set)return;for(i=0;i<set->instance_count;i++){UiControlInstance *instance=&set->instances[i];if(instance->shared.control)ui_shared_release(&instance->shared);else if(instance->object&&!instance->adopted)release_obj(instance->object);}zero(set->instances,sizeof(set->instances));set->instance_count=0;set->screen=0;}
static int ui_controls_build_slider(void *screen,UiControlSet *set,const UiControlSpec *spec,UiControlInstance *instance){UiShared built={0,0},held={0,0};if(!set->context||!spec->native_seam)return 0;((void(*)(UiShared*,void*,const void*))SEAM_OptionsScreen_buildSlider)(&built,screen,spec->native_seam);if(!built.object||!built.control){((ThisFn)SEAM_OptionBuildResult_dtor)(&built);return 0;}((void(*)(UiShared*,void*,void*))SEAM_Shared_copyFromParts)(&held,built.control,built.object);if(!held.object||!held.control){((ThisFn)SEAM_OptionBuildResult_dtor)(&built);return 0;}((PushFn)SEAM_OptionsVector_push)(set->context,(Shared*)&held);((ThisFn)SEAM_Shared_localDtor)(&held);instance->object=built.object;instance->adopted=1;((ThisFn)SEAM_OptionBuildResult_dtor)(&built);return 1;}

int ui_controls_build(void *screen,UiControlSet *set){unsigned i;char label[96];if(!screen||!set||!set->specs||set->spec_count>UI_CONTROL_CAPACITY)return -1;ui_controls_destroy(set);set->screen=screen;for(i=0;i<set->spec_count;i++){const UiControlSpec *spec=&set->specs[i];UiControlInstance *instance=&set->instances[i];void *object=0;int mask=spec->screen_mask?spec->screen_mask:UI_SCREEN_DEFAULT;instance->spec=spec;zero(&instance->shared,sizeof(instance->shared));instance->adopted=0;if(spec->kind==UI_CTRL_SLIDER){if(!ui_controls_build_slider(screen,set,spec,instance)){ui_controls_discard(set);return -1;}set->instance_count=i+1;continue;}ui_localized_label(label,sizeof(label),spec->label_key,spec->label_text);if(spec->kind==UI_CTRL_BUTTON){object=ui_create_button(screen,spec->id,spec->x,spec->y,spec->width,spec->height,label,spec->visible,mask);instance->adopted=1;}else if(spec->kind==UI_CTRL_GRID_BUTTON){object=ui_create_grid_button(screen,spec->id,spec->x,spec->y,spec->width,spec->height,label,spec->visible,mask);if(object&&!ui_shared_from_object(object,&instance->shared)){ui_controls_discard(set);return -1;}}else if(spec->kind==UI_CTRL_SWITCH){if(!ui_create_world_switch_shared(screen,spec->initial_value,spec->id,&instance->shared)){ui_controls_discard(set);return -1;}object=instance->shared.object;}else if(spec->kind==UI_CTRL_DROPDOWN){if(!ui_dropdown_create(screen,spec->id,spec->x,spec->y,spec->width,spec->height,spec->native_seam,&instance->shared)){ui_controls_discard(set);return -1;}object=instance->shared.object;        }else if(spec->kind==UI_CTRL_LABEL){
            object=ui_create_option_label(screen,label);
            if(object&&!ui_shared_from_object(object,&instance->shared)){ui_controls_discard(set);return -1;}
        }else if(spec->kind==UI_CTRL_TAB){
            object=ui_create_button(screen,spec->id,spec->x,spec->y,spec->width,spec->height,label,spec->visible,mask);
            if(object&&!ui_shared_from_object(object,&instance->shared)){ui_controls_discard(set);return -1;}
            if(object)ui_screen_add_tab(screen,&instance->shared);
            instance->adopted=1;
        }else{ui_controls_discard(set);return -1;}if(!object){ui_controls_discard(set);return -1;}instance->object=object;set->instance_count=i+1;}return (int)set->instance_count;}
void ui_controls_destroy(UiControlSet *set){if(!set)return;ui_controls_discard(set);}
int ui_controls_dispatch(UiControlSet *set,void *button_or_event){UiControlInstance *instance;if(!set||!button_or_event)return 0;instance=ui_controls_instance(set,ui_button_id(button_or_event));if(!instance||!instance->spec||!instance->spec->on_press)return 0;instance->spec->on_press(set->screen,instance->object);return 1;}
void *ui_controls_find(const UiControlSet *set,int id){UiControlInstance *instance=ui_controls_instance((UiControlSet*)set,id);return instance?instance->object:0;}
const UiControlSpec *ui_controls_spec(const UiControlSet *set,int id){UiControlInstance *instance=ui_controls_instance((UiControlSet*)set,id);return instance?instance->spec:0;}
const UiShared *ui_controls_shared(const UiControlSet *set,int id){UiControlInstance *instance=ui_controls_instance((UiControlSet*)set,id);return instance&&instance->shared.control?&instance->shared:0;}
void ui_controls_release_shared(UiControlSet *set,int id){UiControlInstance *instance=ui_controls_instance(set,id);if(instance&&instance->shared.control){ui_shared_release(&instance->shared);zero(&instance->shared,sizeof(instance->shared));}}
void ui_controls_adopt(UiControlSet *set,int id){UiControlInstance *instance=ui_controls_instance(set,id);if(instance)instance->adopted=1;}
void ui_controls_set_context(UiControlSet *set,void *context){if(set)set->context=context;}
