#include "ui_runtime.h"
#include "ui_widgets.h"

void *ui_screen_game(void *screen){return screen?((UiScreenView*)screen)->game:0;}
void *ui_screen_client(void *screen){return screen?((UiScreenView*)screen)->client:0;}
void *ui_screen_font(void *screen){return screen?((UiScreenView*)screen)->font:0;}
void *ui_game_small_font(void *screen){void*game=ui_screen_game(screen);return game?*(void**)((u8*)game+0x5C):0;}
void *ui_screen_button_owner(void *screen){return screen?(u8*)screen+0x0C:0;}
void *ui_ingame_pause_button(void *screen){return screen?((UiInGamePlayScreenView*)screen)->pause_button:0;}
int ui_ingame_hud_ready(void *screen){return screen?((UiInGamePlayScreenView*)screen)->hud_delay_timer==0:0;}
int ui_resources_ready(void){return s&&s->resources_ready;}
void ui_element_set_visible(void *element,int visible){UiElementView*e=(UiElementView*)element;if(e){e->active=(u8)visible;e->visible=(u8)visible;}}
void ui_element_set_screen(void *element,int screen_mask){if(element)((UiElementView*)element)->screen_mask=screen_mask;}
void ui_element_capture(void *element,u8 *active,u8 *visible){UiElementView*e=(UiElementView*)element;if(!e)return;if(active)*active=e->active;if(visible)*visible=e->visible;}
void ui_element_restore(void *element,u8 active,u8 visible){UiElementView*e=(UiElementView*)element;if(e){e->active=active;e->visible=visible;}}
void ui_element_copy_horizontal_bounds(void *target,const void *source){UiElementView*to=(UiElementView*)target;const UiElementView*from=(const UiElementView*)source;if(to&&from){to->x=from->x;to->width=from->width;}}
void *ui_option_item_first_child(void *item){UiOptionItemChildrenView*view=(UiOptionItemChildrenView*)item;return view&&view->children.begin&&view->children.begin<view->children.end?view->children.begin[0].object:0;}
const char *ui_option_item_label(void *item){const char*label=0;if(item)cp(&label,&((UiOptionsRowView*)item)->localized_label,sizeof(label));return label?label:"";}
void ui_option_item_set_label(void *item,const char *text){u32 value=0,scratch=0;if(!item)return;((StrCtor)SEAM_StrCtor)(&value,text?text:"",&scratch);((StrAssign)SEAM_StrAssign)(&((UiOptionsRowView*)item)->localized_label,&value);((StrDtor)SEAM_StrDtor)(&value);}
float ui_slider_value(const void *slider){const UiSliderView*view=(const UiSliderView*)slider;return view?view->minimum+(view->maximum-view->minimum)*view->position:0.0f;}
int ui_button_id(void *button){return button?((UiButtonView*)button)->id:-1;}
void ui_screen_add_button(void *screen,UiShared *button){((PushFn)SEAM_SharedPush)(&((UiScreenView*)screen)->buttons,(Shared*)button);}
void ui_screen_add_tab(void *screen,UiShared *tab_button){if(screen&&tab_button)((PushFn)SEAM_SharedPush)(&((UiScreenView*)screen)->tabs,(Shared*)tab_button);}
int ui_screen_selected_tab(void *screen){UiScreenView *v=(UiScreenView*)screen;return v?v->selected_tab:-1;}
void ui_screen_set_tab(void *screen,int tab_index){UiScreenView *v=(UiScreenView*)screen;unsigned count;if(!v||!v->tabs.begin||v->tabs.end<=v->tabs.begin)return;count=(unsigned)(v->tabs.end-v->tabs.begin);if(tab_index<0||(unsigned)tab_index>=count)return;v->selected_tab=tab_index;}
int ui_screen_cycle_tab(void *screen,int delta){unsigned count=ui_screen_tab_count(screen);int current,next;if(count<=1)return -1;current=ui_screen_selected_tab(screen);if(current<0)current=0;next=(current+delta)%(int)count;if(next<0)next+=(int)count;ui_screen_set_tab(screen,next);ui_screen_update_tab_buttons(screen);return next;}
void ui_screen_update_tab_buttons(void *screen){unsigned count=ui_screen_tab_count(screen),i;int selected=ui_screen_selected_tab(screen);for(i=0;i<count;i++){void *tab=ui_screen_tab_at(screen,i);if(tab)ui_button_set_latched(tab,(int)i==selected);}}
unsigned ui_screen_tab_count(void *screen){UiScreenView *v=(UiScreenView*)screen;if(!v||!v->tabs.begin||v->tabs.end<=v->tabs.begin)return 0;return(unsigned)(v->tabs.end-v->tabs.begin);}
void *ui_screen_tab_at(void *screen,unsigned index){UiScreenView *v=(UiScreenView*)screen;if(!v||!v->tabs.begin||v->tabs.begin+index>=v->tabs.end)return 0;return v->tabs.begin[index].object;}
void ui_screen_add_selectable(void*screen,void*object){UiSharedVector*v=&((UiScreenView*)screen)->buttons;UiShared*it;for(it=v->begin;it&&it<v->end;it++)if(it->object==object){((PushFn)SEAM_SharedPush)(&((UiScreenView*)screen)->selectable_components,(Shared*)it);return;}}
void ui_screen_set_selection(void*screen,unsigned index){UiScreenView*v=(UiScreenView*)screen;unsigned count=(unsigned)(v->selectable_components.end-v->selectable_components.begin);if(!count)return;v->selectable_selection=(int)(index%count);((ThisFn)SEAM_Screen_updateComponentSelections)(screen);}
void *ui_screen_selected(void*screen){UiScreenView*v=(UiScreenView*)screen;int i=v->selectable_selection;return i>=0&&v->selectable_components.begin+i<v->selectable_components.end?v->selectable_components.begin[i].object:0;}
int ui_screen_navigate(void*screen,int direction){UiScreenView*v=(UiScreenView*)screen;UiShared*it;UiElementView*selected,*candidate;unsigned index=0,best_index=0;int selected_x,selected_y,dx,dy,primary,secondary,score,best_score=0x7fffffff,found=0;if(!v||!v->selectable_components.begin||v->selectable_components.end<=v->selectable_components.begin)return 0;selected=(UiElementView*)ui_screen_selected(screen);if(!selected)return 0;selected_x=selected->x+selected->width/2;selected_y=selected->y+selected->height/2;for(it=v->selectable_components.begin;it<v->selectable_components.end;it++,index++){candidate=(UiElementView*)it->object;if(!candidate||candidate==selected||!candidate->active||!candidate->visible)continue;dx=candidate->x+candidate->width/2-selected_x;dy=candidate->y+candidate->height/2-selected_y;if(direction==UI_NAV_LEFT){if(dx>=0)continue;primary=-dx;secondary=dy<0?-dy:dy;}else if(direction==UI_NAV_RIGHT){if(dx<=0)continue;primary=dx;secondary=dy<0?-dy:dy;}else if(direction==UI_NAV_UP){if(dy>=0)continue;primary=-dy;secondary=dx<0?-dx:dx;}else if(direction==UI_NAV_DOWN){if(dy<=0)continue;primary=dy;secondary=dx<0?-dx:dx;}else return 0;if(secondary>primary*2+8)continue;score=primary*primary+secondary*secondary*4;if(score<best_score){best_score=score;best_index=index;found=1;}}if(!found)return 0;ui_screen_set_selection(screen,best_index);return 1;}
void ui_container_add_raw(void *container,void *child,int selectable){((ContainerAddChild)SEAM_ContainerAddChild)(container,child,selectable);}
void ui_container_add_shared(void *container,UiShared *child,int selectable){((void(*)(void*,UiShared*,int))SEAM_ContainerAddChildShared)(container,child,selectable);}
unsigned ui_container_child_count(void *container){UiSharedVector*v=&((UiContainerView*)container)->children;return v->begin&&v->end>v->begin?(unsigned)(v->end-v->begin):0;}
void ui_int_vector_push(void *vector,int value){((void(*)(void*,const int*))SEAM_PushRow)(vector,&value);}
int ui_grid_move_appended_row_before(void *container,UiIntVector*rows,void*first,void*second,void*target){UiSharedVector*children;UiShared saved_first,saved_second;unsigned child_count,row_count,target_child,target_row,offset,i;if(!container||!rows||!first||!second||!target)return 0;children=&((UiContainerView*)container)->children;if(!children->begin||!children->end||children->end-children->begin<4||!rows->begin||!rows->end||rows->end<=rows->begin)return 0;child_count=(unsigned)(children->end-children->begin);row_count=(unsigned)(rows->end-rows->begin);if(children->begin[child_count-2].object!=first||children->begin[child_count-1].object!=second)return 0;for(target_child=0;target_child<child_count-2;target_child++)if(children->begin[target_child].object==target)break;if(target_child==child_count-2||target_child==0)return 0;target_child--;offset=0;for(target_row=0;target_row<row_count;target_row++){unsigned width=(unsigned)rows->begin[target_row];if(target_child<offset+width)break;offset+=width;}if(target_row>=row_count-1)return 0;saved_first=children->begin[child_count-2];saved_second=children->begin[child_count-1];for(i=child_count-2;i>target_child;i--)children->begin[i+1]=children->begin[i-1];children->begin[target_child]=saved_first;children->begin[target_child+1]=saved_second;{int saved_width=rows->begin[row_count-1];for(i=row_count-1;i>target_row;i--)rows->begin[i]=rows->begin[i-1];rows->begin[target_row]=saved_width;}return 1;}
void ui_shared_release(UiShared *shared){if(shared&&shared->control)((ReleaseFn)SEAM_SharedRelease)((Shared*)shared);}
void ui_capture_vector(UiSharedVector*v,void **objects,u8 *active,u8 *visible,u32 *count,u32 capacity){UiShared*it,*end;if(!v||!count)return;it=v->begin;end=v->end;while(it&&it<end&&*count<capacity){if(it->object){objects[*count]=it->object;ui_element_capture(it->object,&active[*count],&visible[*count]);(*count)++;}it++;}}
