#include "ui_text_layout.h"

static int measure_slice(void*font,const char*source,unsigned start,unsigned end){u32 handle=0,scratch=0;char text[152];unsigned length=end-start;if(length>151)length=151;cp(text,source+start,length);text[length]=0;((StrCtor)SEAM_StrCtor)(&handle,text,&scratch);length=font?(unsigned)((TextWidth)SEAM_TextWidth)(font,&handle,0,1.0f):length;((StrDtor)SEAM_StrDtor)(&handle);return (int)length;}
static unsigned next_codepoint(const char*text,unsigned at){unsigned next=at+1;while(text[next]&&((u8)text[next]&0xC0u)==0x80u)next++;return next;}

static unsigned wrap_line(void*font,const char*source,unsigned start,int max_width,char*line,unsigned capacity,unsigned*next,int preserve){unsigned boundaries[152],count=0,at,after,low,high,middle,fit_end,line_end,length,i;if(next)*next=start;if(!line||!capacity)return 0;line[0]=0;if(!source)return 0;if(!preserve)while(source[start]==' ')start++;if(!source[start]){if(next)*next=start;return 0;}at=start;while(source[at]&&count<151){after=next_codepoint(source,at);if(after-start>=capacity)break;boundaries[count++]=after;at=after;}if(!count)return 0;if(!font||max_width<=0)low=count;else{low=0;high=count;while(low<high){middle=(low+high+1)/2;if(measure_slice(font,source,start,boundaries[middle-1])<=max_width)low=middle;else high=middle-1;}if(!low)low=1;}fit_end=boundaries[low-1];line_end=fit_end;if(source[fit_end]){for(i=fit_end;i>start;i--)if(source[i-1]==' '){line_end=preserve?i:i-1;break;}}if(line_end==start)line_end=fit_end;length=line_end-start;if(length>=capacity)length=capacity-1;cp(line,source+start,length);if(!preserve)while(length&&line[length-1]==' ')length--;line[length]=0;at=line_end;if(!preserve)while(source[at]==' ')at++;if(next)*next=at;return length;}

unsigned ui_text_wrap_line(void*f,const char*s,unsigned a,int w,char*l,unsigned c,unsigned*n){return wrap_line(f,s,a,w,l,c,n,0);}
unsigned ui_text_wrap_input_line(void*f,const char*s,unsigned a,int w,char*l,unsigned c,unsigned*n){return wrap_line(f,s,a,w,l,c,n,1);}
