#ifndef NUMC3DS_MCPE_PROTOCOL_H
#define NUMC3DS_MCPE_PROTOCOL_H

#include "mcpe_types.h"

#define MCPE_PROTOCOL_VERSION 113u
#define MCPE_GAME_PORT 19132u
#define MCPE_GAME_PORT_V6 19133u
#define MCPE_RAKNET_PROTOCOL_VERSION 10u
#define MCPE_MAX_BATCH_BYTES 1048576u
#define MCPE_MAX_STRING_BYTES 65535u
#define MCPE_MAX_ANNOUNCEMENT_BYTES 1024u

enum McpePacketId {
    MCPE_PACKET_LOGIN = 0x01,
    MCPE_PACKET_PLAY_STATUS = 0x02,
    MCPE_PACKET_SERVER_TO_CLIENT_HANDSHAKE = 0x03,
    MCPE_PACKET_CLIENT_TO_SERVER_HANDSHAKE = 0x04,
    MCPE_PACKET_DISCONNECT = 0x05,
    MCPE_PACKET_RESOURCE_PACKS_INFO = 0x06,
    MCPE_PACKET_RESOURCE_PACK_STACK = 0x07,
    MCPE_PACKET_RESOURCE_PACK_CLIENT_RESPONSE = 0x08,
    MCPE_PACKET_TEXT = 0x09,
    MCPE_PACKET_START_GAME = 0x0b,
    MCPE_PACKET_ADD_PLAYER = 0x0c,
    MCPE_PACKET_PLAYER_LIST = 0x3f,
    MCPE_PACKET_REQUEST_CHUNK_RADIUS = 0x45,
    MCPE_PACKET_CHUNK_RADIUS_UPDATED = 0x46,
    MCPE_PACKET_RESOURCE_PACK_DATA_INFO = 0x53,
    MCPE_PACKET_RESOURCE_PACK_CHUNK_DATA = 0x54,
    MCPE_PACKET_RESOURCE_PACK_CHUNK_REQUEST = 0x55,
    MCPE_PACKET_TRANSFER = 0x56
};

enum McpePlayStatus {
    MCPE_PLAY_STATUS_LOGIN_SUCCESS = 0,
    MCPE_PLAY_STATUS_LOGIN_FAILED_CLIENT = 1,
    MCPE_PLAY_STATUS_LOGIN_FAILED_SERVER = 2,
    MCPE_PLAY_STATUS_PLAYER_SPAWN = 3
};

#endif
