#include "world_transfer_manifest.h"

static unsigned wt_name_len(const char *text){unsigned n=0;if(text)while(text[n])n++;return n;}
static int wt_decode(const char **at,u32 *out){const u8 *p=(const u8*)*at;u32 cp,n,min;unsigned i;if(!p||!*p)return 0;if(p[0]<0x80){cp=p[0];n=1;min=0;}else if(p[0]>=0xC2&&p[0]<=0xDF){cp=p[0]&0x1F;n=2;min=0x80;}else if(p[0]>=0xE0&&p[0]<=0xEF){cp=p[0]&0x0F;n=3;min=0x800;}else if(p[0]>=0xF0&&p[0]<=0xF4){cp=p[0]&7;n=4;min=0x10000;}else return 0;for(i=1;i<n;i++){if((p[i]&0xC0)!=0x80)return 0;cp=(cp<<6)|(p[i]&0x3F);}if(cp<min||cp>0x10FFFFu||(cp>=0xD800u&&cp<=0xDFFFu))return 0;*at=(const char*)(p+n);*out=cp;return 1;}
static unsigned wt_encode(u32 cp,char *out){if(cp<0x80){out[0]=(char)cp;return 1;}if(cp<0x800){out[0]=(char)(0xC0|(cp>>6));out[1]=(char)(0x80|(cp&0x3F));return 2;}if(cp<0x10000){out[0]=(char)(0xE0|(cp>>12));out[1]=(char)(0x80|((cp>>6)&0x3F));out[2]=(char)(0x80|(cp&0x3F));return 3;}out[0]=(char)(0xF0|(cp>>18));out[1]=(char)(0x80|((cp>>12)&0x3F));out[2]=(char)(0x80|((cp>>6)&0x3F));out[3]=(char)(0x80|(cp&0x3F));return 4;}
static int wt_bad_char(u32 cp){return cp<0x20u||cp=='<'||cp=='>'||cp==':'||cp=='"'||cp=='/'||cp=='\\'||cp=='|'||cp=='?'||cp=='*';}

int wt_sanitize_name(const char *source,char *out,unsigned cap){const char *p=source;char encoded[4];unsigned n=0,w,i;u32 codepoint;if(!out||cap<2)return 0;if(!source)source="";while(*p){if(!wt_decode(&p,&codepoint))break;if(wt_bad_char(codepoint))codepoint='_';w=wt_encode(codepoint,encoded);if(n+w>=cap)break;for(i=0;i<w;i++)out[n+i]=encoded[i];n+=w;}while(n&& (out[n-1]=='.'||out[n-1]==' '))n--;if(!n){const char fallback[]="World";if(cap<sizeof(fallback))return 0;for(i=0;i<sizeof(fallback)-1;i++)out[i]=fallback[i];n=sizeof(fallback)-1;}out[n]=0;return 1;}

static u32 wt_mix(u32 hash,const void *data,unsigned size){const u8 *p=(const u8*)data;while(size--){hash^=*p++;hash*=16777619u;}return hash;}
static u32 wt_entry_hash(const char *relative_path,long long size,u32 type){u32 hash=2166136261u;u8 bytes[12];unsigned i,n=wt_name_len(relative_path);hash=wt_mix(hash,relative_path,n);bytes[0]=(u8)type;for(i=0;i<8;i++)bytes[i+1]=(u8)(((unsigned long long)size>>(i*8))&0xFFu);bytes[9]=(u8)(n&0xFFu);bytes[10]=(u8)((n>>8)&0xFFu);bytes[11]=0xA5;return wt_mix(hash,bytes,sizeof(bytes));}
static void wt_hex_u32(char *out,u32 value){static const char digits[]="0123456789abcdef";int i;for(i=7;i>=0;i--)out[7-i]=digits[(value>>(i*4))&0xFu];}
void wt_manifest_reset(WtTransferManifest *manifest){if(manifest)zero(manifest,sizeof(*manifest));}
void wt_manifest_add_directory(WtTransferManifest *manifest,const char *relative_path){u32 h;if(!manifest)return;manifest->entries++;manifest->directories++;h=wt_entry_hash(relative_path,0,1);manifest->path_fingerprint^=h+0x9E3779B9u;}
void wt_manifest_add_file(WtTransferManifest *manifest,const char *relative_path,long long size,u32 content_hash){u32 h;if(!manifest)return;manifest->entries++;manifest->files++;manifest->bytes+=size;h=wt_entry_hash(relative_path,size,2);manifest->path_fingerprint^=h+0x9E3779B9u;manifest->content_fingerprint^=content_hash+h;}
int wt_manifest_equal(const WtTransferManifest *left,const WtTransferManifest *right){return left&&right&&left->entries==right->entries&&left->files==right->files&&left->directories==right->directories&&left->bytes==right->bytes&&left->path_fingerprint==right->path_fingerprint&&left->content_fingerprint==right->content_fingerprint;}
u32 wt_manifest_bytes_hash(u32 seed,const void *data,u32 size){return wt_mix(seed,data,size);}
int wt_manifest_fingerprint_text(const WtTransferManifest *manifest,char *out,unsigned cap){u32 folded;unsigned long long bytes;if(!manifest||!out||cap<25)return 0;bytes=(unsigned long long)manifest->bytes;folded=(u32)bytes^(u32)(bytes>>32)^manifest->entries^manifest->files^manifest->directories;wt_hex_u32(out,manifest->path_fingerprint);wt_hex_u32(out+8,manifest->content_fingerprint);wt_hex_u32(out+16,folded);out[24]=0;return 1;}
